tmux-dev: skip db unless specified

diff --git a/bin/tmux-dev b/bin/tmux-dev
--- a/bin/tmux-dev
+++ b/bin/tmux-dev
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ $# -eq 0 ]; then
-  echo "Usage: tmux-dev project_or_path [-pg]"
+  echo "Usage: tmux-dev project_or_path [-pg|-mysql]"
   exit
 fi
 
@@ -14,10 +14,10 @@ else # full path
 fi
 session_name=${PROJECT//./_}
 
-if [ "$2" == "-pg" ]; then
-  pg_ctl -D /usr/local/var/postgres status >/dev/null || pg_ctl -D /usr/local/var/postgres start || { echo "Cannot start postgresql. Exiting"; exit 1; }
-else
+if [ "$2" == "-mysql" ]; then
   mysql.server status >/dev/null || mysql.server start || { echo "Cannot start mysql. Exiting"; exit 1; }
+elif [ "$2" == "-pg" ]; then
+  pg_ctl -D /usr/local/var/postgres status >/dev/null || pg_ctl -D /usr/local/var/postgres start || { echo "Cannot start postgresql. Exiting"; exit 1; }
 fi
 
 if tmux has -t $session_name 2>/dev/null; then
