Update tmux-dev to support postgres and not assume gitsh is installed

diff --git a/bin/tmux-dev b/bin/tmux-dev
--- a/bin/tmux-dev
+++ b/bin/tmux-dev
@@ -1,10 +1,24 @@
 #!/bin/bash
 
-PROJECT="${1:-onsitehd.com}"
-WORKING_DIR="${HOME}/Sites/${PROJECT}"
+if [ $# -eq 0 ]; then
+  echo "Usage: tmux-dev project_or_path [-pg]"
+  exit
+fi
+
+if [ "${1/\//}" == "${1}" ]; then # project name
+  PROJECT="${1}"
+  WORKING_DIR="${HOME}/Sites/${PROJECT}"
+else # full path
+  WORKING_DIR="${1}"
+  PROJECT=$(basename "$1")
+fi
 session_name=${PROJECT//./_}
 
-mysql.server status >/dev/null || mysql.server start || { echo "Cannot start mysql. Exiting"; exit 1; }
+if [ "$2" == "-pg" ]; then
+  pg_ctl -D /usr/local/var/postgres status >/dev/null || pg_ctl -D /usr/local/var/postgres start || { echo "Cannot start postgresql. Exiting"; exit 1; }
+else
+  mysql.server status >/dev/null || mysql.server start || { echo "Cannot start mysql. Exiting"; exit 1; }
+fi
 
 if tmux has -t $session_name 2>/dev/null; then
   exec tmux attach-session -t $session_name
@@ -16,7 +30,7 @@ tmux rename-window server
 tmux new-window -n vim -c "$WORKING_DIR"
 tmux new-window -n test -c "$WORKING_DIR"
 tmux new-window -n console -c "$WORKING_DIR"
-tmux new-window -n gitsh -c "$WORKING_DIR" gitsh
+tmux new-window -n git -c "$WORKING_DIR"
 tmux new-window -n remote -c "$WORKING_DIR"
 
 sleep 1
@@ -25,7 +39,12 @@ tmux select-window -t server
 tmux send-keys 'ras'
 tmux select-window -t console
 tmux send-keys 'rails c'
-tmux select-window -t gitsh
-tmux send-keys 'lh' C-m C-m
+tmux select-window -t git
+if type gitsh >/dev/null 2>&1; then
+  tmux send-keys 'gitsh' C-m
+  tmux send-keys 'lh' C-m C-m
+else
+  tmux send-keys 'git lh' C-m 'git st' C-m
+fi
 
 tmux attach-session -t $session_name
